spring:
  application:
      name: auth-security
  devtools:
    restart:
      enabled: true

server:
  port: 9000

eureka: 
  client: 
    instance: 
      preferIpAddress: true
    serviceUrl: 
      defaultZone: "${EUREKA_URI:http://localhost:8761/eureka/}"

logging:
  level:
    org.springframework.security: TRACE